name: CI Build & Release ROS 2 Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS 2 Rolling
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling

      - name: Install dependencies
        run: |
          sudo apt update
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y

      - name: Build package
        run: |
          colcon build --event-handlers console_direct+

      # - name: Run tests
      #   run: |
      #     colcon test --event-handlers console_direct+
      #     colcon test-result --verbose

  release:
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ROS 2 package release for ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
